### ISSUE TITLE
可以请教一下octopus的配置问题吗？

### ISSUE THREAD

**Issue by EnochChan97** [ischansgithub/MyProjectExperience#1]
您好，我是从dirt的isssues里看到你也有用过octopus。在我在安装dirt过程中遇到下面的问题:
我的环境是：ubuntu18.04 python2.7 tensorflow-gpu2.1.0

Traceback (most recent call last):
  File "infer_single.py", line 9, in <module>
    from model.octopus import Octopus
  File "/home/chensien/octopus/model/octopus.py", line 16, in <module>
    from render.render_layer import RenderLayer
  File "/home/chensien/octopus/render/render_layer.py", line 1, in <module>
    from render import render_colored_batch
  File "/home/chensien/octopus/render/render.py", line 1, in <module>
    import dirt
  File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/__init__.py", line 2, in <module>
    from .rasterise_ops import rasterise, rasterise_batch, rasterise_deferred, rasterise_batch_deferred
  File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/rasterise_ops.py", line 6, in <module>
    _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
  File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/tensorflow_core/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory

希望您能提供一些帮助，万分感谢！

**Comment by ischansgithub** [comment]
> 您好，我是从dirt的isssues里看到你也有用过octopus。在我在安装dirt过程中遇到下面的问题:
> 我的环境是：ubuntu18.04 python2.7 tensorflow-gpu2.1.0
> 
> Traceback (most recent call last):
> File "infer_single.py", line 9, in 
> from model.octopus import Octopus
> File "/home/chensien/octopus/model/octopus.py", line 16, in 
> from render.render_layer import RenderLayer
> File "/home/chensien/octopus/render/render_layer.py", line 1, in 
> from render import render_colored_batch
> File "/home/chensien/octopus/render/render.py", line 1, in 
> import dirt
> File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/**init**.py", line 2, in 
> from .rasterise_ops import rasterise, rasterise_batch, rasterise_deferred, rasterise_batch_deferred
> File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/dirt/rasterise_ops.py", line 6, in 
> _rasterise_module = tf.load_op_library(_lib_path + '/librasterise.so')
> File "/home/chensien/anaconda3/envs/octopus/lib/python2.7/site-packages/tensorflow_core/python/framework/load_library.py", line 58, in load_op_library
> lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory
> 
> 希望您能提供一些帮助，万分感谢！

有关octupus的项目在我外出实习后移交给其他同门了，加上我对octupus的认知止步于论文，具体技节、代码细节不是很清楚，不好意思兄弟，恐怕不能帮到你什么忙。

**Comment by EnochChan97** [comment]
没事没事，谢谢老哥，看了你记录的笔记和日常，太优秀了～祝老哥科研顺利～

**Comment by ischansgithub** [comment]
> 没事没事，谢谢老哥，看了你记录的笔记和日常，太优秀了～祝老哥科研顺利～

谢谢 ^ ^
